/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package  Application;

import BDD.Parameter;
import BDD.ResultSetTableModel;
import BDD.db_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nathou
 */
public class Caissier extends javax.swing.JFrame {

    /**
     * Creates new form cachier
     */
    
    ResultSet rs;
    db_connection db;
    int old, dec, now;
    public Caissier() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        
        initComponents();
        table();
        jam();
        this.setLocationRelativeTo(null);
    }

    public void table() {
        String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
        rs = db.querySelect(colon, "medicament");
        tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
    }

    public void importer() {
        String colon[] = {"num_facture","code_med","reference","prix_vente","stock_sortie","subtotal"};
        rs = db.fcSelectCommand(colon, "vente", "num_facture='" + txtfac.getText() + "'");
        tbl_ven.setModel(DbUtils.resultSetToTableModel(rs));
    }
     public void jam() {
        Date s = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat jam = new SimpleDateFormat("HH:mm");
        lbl1.setText(jam.format(s));
        lbl2.setText(tgl.format(s));}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_res = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        txtrech = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfou = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpri = new javax.swing.JTextField();
        txtrem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnou = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtsto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbltot1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtfac = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ven = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbltot2 = new javax.swing.JLabel();
        txtcas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtrenb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 725));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Caissier");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 60, 23);

        tbl_res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "code_med", "reference", "designation", "date_perem", "fournisseur", "remise", "prix", "stock "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_resMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_res);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 1000, 90);

        jButton7.setText("actualiser");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(830, 10, 80, 20);

        jButton8.setText("sortir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(920, 10, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("recherche par catégorie :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 130, 250, 20);

        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "code_med", "reference", "deseignation", "date_perem", "fournisseur", "remise", "prix", "stock" }));
        getContentPane().add(comrech);
        comrech.setBounds(60, 160, 240, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("recherche ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 200, 128, 30);
        getContentPane().add(txtrech);
        txtrech.setBounds(150, 200, 180, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Code Medicament :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 250, 120, 17);

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });
        getContentPane().add(txtcod);
        txtcod.setBounds(130, 240, 160, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Reference     :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 100, 17);

        txtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrefActionPerformed(evt);
            }
        });
        getContentPane().add(txtref);
        txtref.setBounds(130, 280, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Date Peremption :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 330, 110, 17);

        txtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtranActionPerformed(evt);
            }
        });
        getContentPane().add(txtran);
        txtran.setBounds(130, 320, 160, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Fournisseur :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 370, 100, 17);

        txtfou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfouActionPerformed(evt);
            }
        });
        getContentPane().add(txtfou);
        txtfou.setBounds(130, 360, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Prix        :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 410, 100, 17);

        txtpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriActionPerformed(evt);
            }
        });
        getContentPane().add(txtpri);
        txtpri.setBounds(130, 400, 160, 30);

        txtrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremActionPerformed(evt);
            }
        });
        getContentPane().add(txtrem);
        txtrem.setBounds(130, 440, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Remise %     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 450, 100, 17);

        txtnou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnouActionPerformed(evt);
            }
        });
        getContentPane().add(txtnou);
        txtnou.setBounds(130, 480, 160, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Nouveau Prix  :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 490, 100, 17);

        txtsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstoActionPerformed(evt);
            }
        });
        txtsto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstoKeyReleased(evt);
            }
        });
        getContentPane().add(txtsto);
        txtsto.setBounds(130, 530, 160, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Stock sorti  :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 540, 100, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("Total : ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 580, 70, 30);

        lbltot1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot1.setText("0");
        lbltot1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbltot1KeyReleased(evt);
            }
        });
        getContentPane().add(lbltot1);
        lbltot1.setBounds(90, 580, 170, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Ajouter au vente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 640, 260, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setText("Vente");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(680, 150, 60, 24);

        lbl2.setText("jLabel17");
        getContentPane().add(lbl2);
        lbl2.setBounds(790, 140, 150, 16);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl1.setText("jLabel12");
        getContentPane().add(lbl1);
        lbl1.setBounds(790, 170, 150, 15);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Num de facture :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(420, 270, 100, 17);

        txtfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfacActionPerformed(evt);
            }
        });
        getContentPane().add(txtfac);
        txtfac.setBounds(530, 260, 160, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setText("recherche ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 260, 120, 24);

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(830, 260, 110, 24);

        tbl_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "num_facture", "code_med", "reference", "Prix de vente", "Stock sorti", "total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_ven);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 310, 630, 110);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Total ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(510, 450, 110, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Facture :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(590, 450, 90, 30);

        lbltot2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbltot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltot2.setText("0");
        getContentPane().add(lbltot2);
        lbltot2.setBounds(720, 450, 190, 30);

        txtcas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcasKeyReleased(evt);
            }
        });
        getContentPane().add(txtcas);
        txtcas.setBounds(560, 520, 130, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("payer :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(500, 520, 60, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("reste à payer :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(700, 540, 120, 30);
        getContentPane().add(txtpay);
        txtpay.setBounds(830, 540, 130, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 600, 350, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(590, 650, 350, 30);
        getContentPane().add(txtrenb);
        txtrenb.setBounds(830, 502, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("à rembourser :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 510, 110, 17);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ericp\\Downloads\\Documents\\Projet\\Code\\Gestion_Stock_Pharmacie\\background\\c.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1010, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_resMouseClicked
        txtcod.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 0)));
        txtref.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 1)));
        txtran.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 3)));
        txtfou.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 4)));
        txtrem.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 5)));
        txtpri.setText(String.valueOf(tbl_res.getValueAt(tbl_res.getSelectedRow(), 6)));
       cout();
    }//GEN-LAST:event_tbl_resMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Recu r = new Recu();
        r.setVisible(true);
        payaprés();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    private void txtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrefActionPerformed

    private void txtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtranActionPerformed

    private void txtfouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfouActionPerformed

    private void txtpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriActionPerformed

    private void txtremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremActionPerformed

    private void txtnouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnouActionPerformed

    private void txtstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoActionPerformed

    private void txtfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfacActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (txtrech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir le champ");
        } else {
            if (comrech.getSelectedItem().equals("code_med")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "code_produit LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("reference")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "reference LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("deseignation")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "deseignation LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
                } else if (comrech.getSelectedItem().equals("date_perem")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "rangement LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("fournisseur")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "fournisseur LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
                } else if (comrech.getSelectedItem().equals("remise")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "remise LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("prix")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "prix LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
                } else if (comrech.getSelectedItem().equals("stock")) {
                String colon[] = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
                rs = db.fcSelectCommand(colon, "medicament", "stock LIKE '" + txtrech.getText() + "' ");
                tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtcod.getText().equals("") || txtref.getText().equals("") || txtran.getText().equals("")
                || txtfou.getText().equals("") || txtrem.getText().equals("") || txtpri.getText().equals("") || txtnou.getText().equals("")|| txtsto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir vos donneé");
        } else if (txtfac.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez entrez le numéro de facture");
        } else try {
            if (!test_stock()) {
                JOptionPane.showMessageDialog(this, "le stock est Limiter");
            } else {    
                String[] colon = {"num_facture","code_med", "reference", "prix_vente", "stock_sortie", "subtotal"};
                String[] isi = {txtfac.getText(), txtcod.getText(), txtref.getText(), txtnou.getText(), txtsto.getText(), lbltot1.getText()};
                System.out.println(db.queryInsert("vente", colon, isi));
                try {
                    if (!test_stock()) {
                        JOptionPane.showMessageDialog(this, "le stock est Limiter");
                    } else {
                        def(); //true
                        table(); //true
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Caissier.class.getName()).log(Level.SEVERE, null, ex);
                    System.err.println("\n"+ex);
                }
                subtotal();
                importer();
                total();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Caissier.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        importer();
        total();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = String.valueOf(tbl_ven.getValueAt(tbl_ven.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Vous etes sur le point de supprimer une facture", "Attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "id=" + id);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String invoice = txtfac.getText();
        if (JOptionPane.showConfirmDialog(this,"Vous etes sur le point d'annuler la facture ","attention", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("vente", "num_facture=" + invoice);
        } else {
            return;
        }
        importer();
        total();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtstoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstoKeyReleased
    subtotal();        // TODO add your handling code here:
    }//GEN-LAST:event_txtstoKeyReleased

    private void txtcasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcasKeyReleased
    payaprés();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcasKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     table();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void lbltot1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbltot1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbltot1KeyReleased

    /**
     * @param args the command line arguments
     */
    
    public void cout() {
        double a = Double.parseDouble(txtpri.getText());
        double b = Double.parseDouble(txtrem.getText());
        double c = a - a * (b / 100);
        txtnou.setText(String.valueOf(c));
    }
     public void subtotal() {
        double a = Double.parseDouble(txtnou.getText());
        double b = Double.parseDouble(txtsto.getText());
        double c = a * b;
        lbltot1.setText(String.valueOf(c));
    }
        
     
      public void total() {
        rs = db.exécutionQuery("SELECT SUM(subtotal) as subtotal FROM vente WHERE num_facture = '" + txtfac.getText() + "'");
        try {
            rs.next();
            lbltot2.setText(rs.getString("subtotal"));
        } catch (SQLException ex) {
            Logger.getLogger(Caissier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       public boolean test_stock() throws SQLException {
        boolean teststock;
        rs = db.querySelectAll("medicament","code_med='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        if (old < dec) {
            teststock = false;
        } else {
            teststock = true;
        }
        return teststock;
    }

    public void def() throws SQLException {
        rs = db.querySelectAll("medicament", "code_med='" + txtcod.getText() + "'");
        while (rs.next()) {
            old = rs.getInt("stock");
        }
        dec = Integer.parseInt(txtsto.getText());
        now = old - dec;
         String nvstock = Integer.toString(now);

        String a = String.valueOf(nvstock);
        String[] colon = {"stock"};
        String[] isi = {a};
        System.out.println(db.queryUpdate("medicament", colon, isi, "code_med='" + txtcod.getText() + "'"));
    }

    public void payaprés() {
        int a = Integer.parseInt(lbltot2.getText());
        int b = Integer.parseInt(txtcas.getText());
        int c = b - a;
        int d = b - a;
         if (c < 0){
          int e = c * -1;
            txtpay.setText(Integer.toString(e));
        } else {
            txtpay.setText(Integer.toString(0));
        }
        if (d > 0){
            txtrenb.setText(Integer.toString(d));
        } else {
            txtrenb.setText(Integer.toString(0));
        }
    }
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caissier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caissier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox comrech;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl1;
    public static javax.swing.JLabel lbl2;
    public static javax.swing.JLabel lbltot1;
    public static javax.swing.JLabel lbltot2;
    public static javax.swing.JTable tbl_res;
    public static javax.swing.JTable tbl_ven;
    public static javax.swing.JTextField txtcas;
    public static javax.swing.JTextField txtcod;
    public static javax.swing.JTextField txtfac;
    public static javax.swing.JTextField txtfou;
    public static javax.swing.JTextField txtnou;
    public static javax.swing.JTextField txtpay;
    public static javax.swing.JTextField txtpri;
    public static javax.swing.JTextField txtran;
    public static javax.swing.JTextField txtrech;
    public static javax.swing.JTextField txtref;
    public static javax.swing.JTextField txtrem;
    private javax.swing.JTextField txtrenb;
    public static javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
