/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Application;

import BDD.Parameter;
import BDD.ResultSetTableModel;
import BDD.db_connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Nathou
 */
public class Medicament extends javax.swing.JFrame {

    /**
     * Creates new form utilisateur
     */
    ResultSet rs;
    db_connection db;
    public Medicament() {
        db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        table();
        this.setLocationRelativeTo(null);
    }
     public void table() {
        String t[] = {"id","code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
        rs = db.querySelect(t, "medicament");
        tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
    }
     void actualiser() {
        txtid.setText("");
        txtref.setText("");
        txtdes.setText("");
        txtran.setText("");
        txtfou.setText("");
        txtrem.setText("");
        txtpri.setText("");
        txtsto.setText("");}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_med = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfou = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpri = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox();
        comrech2 = new javax.swing.JButton();
        txtrech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(865, 590));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gestion des Medicaments");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 40, 480, 50);

        tbl_med.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "code_med", "reference", "designation", "date_perem", "fournisseur", "remise", "prix", "stock "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_medMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_med);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 840, 150);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 280, 120, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 280, 110, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 280, 130, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(420, 280, 130, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Code Medicament   :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 350, 110, 27);
        getContentPane().add(txtid);
        txtid.setBounds(150, 340, 100, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reference    :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 400, 70, 27);
        getContentPane().add(txtref);
        txtref.setBounds(150, 390, 100, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Designation    :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 450, 90, 27);
        getContentPane().add(txtdes);
        txtdes.setBounds(150, 440, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date Peremption  :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 500, 100, 27);
        getContentPane().add(txtran);
        txtran.setBounds(150, 490, 100, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fournisseur  :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 350, 90, 20);
        getContentPane().add(txtfou);
        txtfou.setBounds(380, 340, 100, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Remise % :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 400, 70, 27);
        getContentPane().add(txtrem);
        txtrem.setBounds(380, 390, 100, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prix   :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 450, 70, 27);
        getContentPane().add(txtpri);
        txtpri.setBounds(380, 440, 100, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stock   :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 500, 70, 27);
        getContentPane().add(txtsto);
        txtsto.setBounds(380, 490, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("recherche par catégorie :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 280, 250, 30);

        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "code_med", "reference", "deseignation", "date_perem", "fournisseur", "remise", "prix", "stock" }));
        comrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comrechActionPerformed(evt);
            }
        });
        getContentPane().add(comrech);
        comrech.setBounds(570, 320, 240, 40);

        comrech2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comrech2.setText("Recherche");
        comrech2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comrech2ActionPerformed(evt);
            }
        });
        getContentPane().add(comrech2);
        comrech2.setBounds(510, 380, 120, 40);
        getContentPane().add(txtrech);
        txtrech.setBounds(650, 380, 180, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 450, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ericp\\Downloads\\Documents\\Projet\\Code\\Gestion_Stock_Pharmacie\\background\\sombre\\m.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtid.getText().equals("") || txtref.getText().equals("") || txtdes.getText().equals("")
                || txtfou.getText().equals("") || txtran.getText().equals("") || txtrem.getText().equals("")
                || txtpri.getText().equals("") || txtsto.getText().equals("")
                ) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tout les champs");
        } else {
            String[] colon = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
            String[] inf = {txtid.getText(), txtref.getText(), txtdes.getText(),txtran.getText(),txtfou.getText()
            ,txtrem.getText(),txtpri.getText(),txtsto.getText()};
            System.out.println(db.queryInsert("medicament", colon, inf));
            table();
            actualiser();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtid.getText().equals("") || txtref.getText().equals("") || txtdes.getText().equals("")
                || txtfou.getText().equals("") || txtran.getText().equals("") || txtrem.getText().equals("")
                || txtpri.getText().equals("") || txtsto.getText().equals("")
                ) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tout les champs");
        } else {
                  String[] colon = {"code_med","reference","deseignation","date_perem","fournisseur","remise","prix","stock"};
              String[] inf = {txtid.getText(), txtref.getText(), txtdes.getText(),txtran.getText(),txtfou.getText()
            ,txtrem.getText(),txtpri.getText(),txtsto.getText()};
            String id = String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 0));
            System.out.println(db.queryUpdate("medicament", colon, inf, "id='" + id + "'"));
            table();
            actualiser();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Etes-vous sur le point de supprimer un produit", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("medicament", "id=" + id);
        } else {
            return;
        }
        table();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        actualiser();
        table();        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_medMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_medMouseClicked
        txtid.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 1)));
        txtref.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 2)));
        txtdes.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 3)));
        txtran.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 4)));
        txtfou.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 5)));
        txtrem.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 6)));
        txtpri.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 7)));
        txtsto.setText(String.valueOf(tbl_med.getValueAt(tbl_med.getSelectedRow(), 8)));
    }//GEN-LAST:event_tbl_medMouseClicked

    private void comrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comrechActionPerformed

    private void comrech2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comrech2ActionPerformed
        // TODO add your handling code here:
        if (txtrech.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir le champ");
            } else {
            if (comrech.getSelectedItem().equals("code_med")) {
                rs = db.querySelectAll("medicament", "code_med LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("reference")) {
                rs = db.querySelectAll("medicament", "reference LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("deseignation")) {
                rs = db.querySelectAll("medicament", "deseignation LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("date_perem")) {
                rs = db.querySelectAll("medicament", "date_perem LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("fournisseur")) {
                rs = db.querySelectAll("medicament", "fournisseur LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("remise")) {
                rs = db.querySelectAll("medicament", "remise LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("prix")) {
                rs = db.querySelectAll("medicament", "prix LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            } else if (comrech.getSelectedItem().equals("stock")) {
                rs = db.querySelectAll("medicament", "stock LIKE '%" + txtrech.getText() + "%' ");
                tbl_med.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }
    }//GEN-LAST:event_comrech2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comrech;
    private javax.swing.JButton comrech2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_med;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtfou;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpri;
    private javax.swing.JTextField txtran;
    private javax.swing.JTextField txtrech;
    private javax.swing.JTextField txtref;
    private javax.swing.JTextField txtrem;
    private javax.swing.JTextField txtsto;
    // End of variables declaration//GEN-END:variables
}
